export const CONSTRUCTOR_GET_ORDERNUM:         'CONSTRUCTOR_GET_ORDERNUM'          = 'CONSTRUCTOR_GET_ORDERNUM';
export const CONSTRUCTOR_GET_ORDERNUM_SUCCESS: 'CONSTRUCTOR_GET_ORDERNUM_SUCCESS'  = 'CONSTRUCTOR_GET_ORDERNUM_SUCCESS';
export const CONSTRUCTOR_GET_ORDERNUM_FAILED:  'CONSTRUCTOR_GET_ORDERNUM_FAILED'   = 'CONSTRUCTOR_GET_ORDERNUM_FAILED';
export const CONSTRUCTOR_CLEAR_ORDERNUM:       'CONSTRUCTOR_CLEAR_ORDERNUM'        = 'CONSTRUCTOR_CLEAR_ORDERNUM';