export const USER_DATA_UPDATE:      'USER_DATA_UPDATE' =     'USER_DATA_UPDATE';
export const USER_ROLLBACK:         'USER_ROLLBACK' =        'USER_ROLLBACK';
export const USER_ROLLBACK_UPDATE:  'USER_ROLLBACK_UPDATE' = 'USER_ROLLBACK_UPDATE';

export const USER_REG:              'USER_REG' =             'USER_REG';
export const USER_REG_SUCCESS:      'USER_REG_SUCCESS' =     'USER_REG_SUCCESS';
export const USER_REG_FAILED:       'USER_REG_FAILED' =      'USER_REG_FAILED';

export const USER_LOGIN:            'USER_LOGIN' =           'USER_LOGIN';
export const USER_LOGIN_SUCCESS:    'USER_LOGIN_SUCCESS' =   'USER_LOGIN_SUCCESS';
export const USER_LOGIN_FAILED:     'USER_LOGIN_FAILED' =    'USER_LOGIN_FAILED';

export const USER_LOGOUT:           'USER_LOGOUT'  =         'USER_LOGOUT';
export const USER_LOGOUT_SUCCESS:   'USER_LOGOUT_SUCCESS' =  'USER_LOGOUT_SUCCESS';
export const USER_LOGOUT_FAILED:    'USER_LOGOUT_FAILED'=    'USER_LOGOUT_FAILED';

export const USER_PASSWORD_REQUEST:         'USER_PASSWORD_REQUEST'=          'USER_PASSWORD_REQUEST';
export const USER_PASSWORD_REQUEST_SUCCESS: 'USER_PASSWORD_REQUEST_SUCCESS' = 'USER_PASSWORD_REQUEST_SUCCESS';
export const USER_PASSWORD_REQUEST_FAILED:  'USER_PASSWORD_REQUEST_FAILED' =  'USER_PASSWORD_REQUEST_FAILED';

export const USER_PASSWORD_RESET:           'USER_PASSWORD_RESET'  =          'USER_PASSWORD_RESET';
export const USER_PASSWORD_RESET_SUCCESS:   'USER_PASSWORD_RESET_SUCCESS' =   'USER_PASSWORD_RESET_SUCCESS';
export const USER_PASSWORD_RESET_FAILED:    'USER_PASSWORD_RESET_FAILED' =    'USER_PASSWORD_RESET_FAILED';

export const USER_GET_USER_DATA:            'USER_GET_USER_DATA' =            'USER_GET_USER_DATA';
export const USER_GET_USER_DATA_SUCCESS:    'USER_GET_USER_DATA_SUCCESS' =    'USER_GET_USER_DATA_SUCCESS';
export const USER_GET_USER_DATA_FAILED:     'USER_GET_USER_DATA_FAILED' =     'USER_GET_USER_DATA_FAILED';

export const USER_UPDATE_USER_DATA:         'USER_UPDATE_USER_DATA' =         'USER_UPDATE_USER_DATA';
export const USER_UPDATE_USER_DATA_SUCCESS: 'USER_UPDATE_USER_DATA_SUCCESS' = 'USER_UPDATE_USER_DATA_SUCCESS';
export const USER_UPDATE_USER_DATA_FAILED:  'USER_UPDATE_USER_DATA_FAILED' =  'USER_UPDATE_USER_DATA_FAILED';